import "../../style.css";
import "./style.css";
import { DesktopClient } from "./client.ts";
import { AudioClient } from "./audio.ts";
import { AgentClient } from "./agent.ts";
import { MediaClient } from "./media.ts";
import { ProfileClient } from "./profile.ts";
import { nativeTransport, nativeAgentTransport, nativeAudioTransport, nativeMediaTransport, nativeProfileTransport } from "./native.ts";
import { mountDesktop } from "./view.ts";
const client = new DesktopClient(nativeTransport);
const agent = new AgentClient(nativeAgentTransport);
void agent.connect();
const audio = new AudioClient(nativeAudioTransport);
void audio.connect();
const media = new MediaClient(nativeMediaTransport);
void media.connect();
const profiles = new ProfileClient(nativeProfileTransport);
void profiles.connect();
const disposeView = mountDesktop(document.getElementById("app")!, client, agent, audio, media, profiles);
void client.connect();
const focus = () => { if (client.status !== "saving") void client.connect(); };
addEventListener("focus", focus);
addEventListener("pagehide", () => { removeEventListener("focus", focus); disposeView(); client.dispose(); agent.dispose(); audio.dispose(); media.dispose(); profiles.dispose(); }, { once: true });
